### PR TITLE
Updated Client Side Cron Regex

### PR DESCRIPTION
**Pull request by KanniShashankh**
## What does this PR do?

Updated the Regex Pattern to correctly validate the cron syntax.
Mentioned the allowed values in a comment.

## Test Plan

I tried a few statements and they validated correctly.

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/5719

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Review by navneetbz — APPROVED** [review]
LGTM

**Review by stnguyen90 — DISMISSED** [review]
Great work! Please make sure the linter and tests pass.

**Comment by KanniShashankh** [comment]
> Great work! Please make sure the linter and tests pass.

Done with the linter test, Investigating the problem in Unit testing which incorrectly validates the tests. Will push a commit soon

**Comment by stnguyen90** [comment]
@KanniShashankh there still seems to be a problem with the linter 🧐

**Comment by KanniShashankh** [comment]
@stnguyen90 To keep the regex simple, since this is just a frontend check, i have very much simplified the expression to match 5 segments of cron. Please let me know if i need to add something :)

**Pull request merged**
