### PR TITLE
Fix: Runtime versions in templates

### PR DESCRIPTION
**Pull request by Meldiron**
## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
The Runtime sidebar isn't consistent. In this list view, they're check boxes:

image

But when I look at the details of a function, it's the runtime w/ versions:

image

In addition, if I create a function from the function templates list page

image

my runtime dropdown is empty:

image

If I open it from template details or the cover, it's fine:

image

**Comment by loks0n** [comment]
> The Runtime sidebar isn't consistent. In this list view, they're check boxes:
> But when I look at the details of a function, it's the runtime w/ versions:

Made this change on purpose, as I don't image you typically search by runtime version rather than runtime, where do you think versions should be included?

> In addition, if I create a function from the function templates list page my runtime dropdown is empty

Fixed.

**Comment by stnguyen90** [comment]
> Made this change on purpose, as I don't image you typically search by runtime version rather than runtime, where do you think versions should be included?

@loks0n, we need Design involved and whatever we decide, it should be consistent between the list and details pages.

**Review by stnguyen90 — APPROVED** [review]
functionality working fine. i was able to create a new function using git with a different node runtime version than previously on 1.4.2.

image

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
