### PR TITLE
Fix redirect after deleting org

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

Fixes https://github.com/appwrite/appwrite/issues/7736, https://github.com/appwrite/console/issues/1030

## Test Plan

Deleting an org with another org:

https://github.com/appwrite/console/assets/1477010/baf46c82-5993-4d38-9b4a-df36db257c06

Deleting an org without any other orgs:

https://github.com/appwrite/console/assets/1477010/0261fbb0-8718-46ab-afb0-b4ba7f70951d

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/7736
* https://github.com/appwrite/console/issues/1030

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Comment by abnegate** [comment]
For the case where there's still another org, there's a flash (most noticeable on the org user avatar) , is it possible to avoid that?

**Comment by stnguyen90** [comment]
@abnegate, what did you mean by: 

> the org user avatar

The avatar at the top right of the console?

**Comment by stnguyen90** [comment]
Oh, you mean the avatar at the bottom left of the organization card? 

Probably not because it's an image that needs to load

**Comment by abnegate** [comment]
@stnguyen90 Looks like it loads, disappears, then loads again, and the placeholder is not in the same position as the loaded image

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
