### PR TITLE
Fix 5204 Use standard syntax for web code sample when loading the appwrite script

### PR DESCRIPTION
**Pull request by spontaneouscombustion**
## What does this PR do?

fixes the sample web code to use the standard syntax instead of self-closing syntax when loading the appwrite script

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/5204

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by spontaneouscombustion** [comment]
> 

sorry. i am not familiar with svelte. I just noticed about the script end tag on the same file. that maybe the cause of this build issue. added commit to fix it.

**Review by x0samnan — APPROVED** [review]

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Great PR! 🤯 We left some comments during the review, please check them out.

**Comment by spontaneouscombustion** [comment]
removed excess backtick.

**Comment by TorstenDittmann** [comment]
@spontaneouscombustion looks good, can you run the formatter and we can merge then 👍🏻

**Comment by x0samnan** [comment]
@spontaneouscombustion Follow along [this](https://stackoverflow.com/questions/69797806/code-style-issues-found-in-the-above-files-forgot-to-run-prettier) and the issue will be fixed and will be ready to merge.

**Comment by stnguyen90** [comment]
@spontaneouscombustion please run `npm run format` to fix the linting problem.

**Comment by stnguyen90** [comment]
Closing due to inactivity.

**Pull request closed without merging**
