### PR TITLE
Add a generic OIDC OAuth2 provider

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

Add an OIDC OAuth2 Provider to the Console

## Test Plan

image

image

image

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/4299
* https://github.com/appwrite/appwrite/pull/5449

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by TorstenDittmann — APPROVED** [review]
lets wait for backend PR 👍🏻

**Comment by binaryfire** [comment]
Nice work @stnguyen90. Hoping this gets merged soon. Will be great to have Keycloak support.

**Comment by eldadfux** [comment]
It should be OIDC in the UI, and not Oidc

**Comment by stnguyen90** [comment]
> It should be OIDC in the UI, and not Oidc

@eldadfux, the API returns Oidc for the name and we use that in the Console: 

https://github.com/appwrite/console/blob/8fdaaf2885ebae81f5e27271ce9b8e46efb8efbc/src/routes/console/project-%5Bproject%5D/auth/settings/%2Bpage.svelte#L88

We would have to add and maintain a list of exceptions in the console repo somewhere. That okay?

**Comment by eldadfux** [comment]
> > It should be OIDC in the UI, and not Oidc
> 
> @eldadfux, the API returns Oidc for the name and we use that in the Console:
> 
> https://github.com/appwrite/console/blob/8fdaaf2885ebae81f5e27271ce9b8e46efb8efbc/src/routes/console/project-%5Bproject%5D/auth/settings/%2Bpage.svelte#L88
> 
> We would have to add and maintain a list of exceptions in the console repo somewhere. That okay?

I think we should avoid that. I think we need to find a better way to expose the [name](https://github.com/appwrite/appwrite/blob/feat-4299-oidc-oauth2-provider/app/config/providers.php#L205), which endpoint do we use for getting it right now?

**Comment by stnguyen90** [comment]
> I think we should avoid that. I think we need to find a better way to expose the [name](https://github.com/appwrite/appwrite/blob/feat-4299-oidc-oauth2-provider/app/config/providers.php#L205), which endpoint do we use for getting it right now?

@eldadfux, it comes from the List/Get Projects endpoints. The providers attribute is a list of providers where name is the provider key.

https://github.com/appwrite/appwrite/blob/e12a5738aa56bcbb6dc41c8b5b0d201bb2eae5e7/src/Appwrite/Utopia/Response/Model/Project.php#L276 

Btw, our setup is really limiting since it makes it so that we can only have 1 of each OAuth2 provider.

**Comment by stnguyen90** [comment]
> I don't see a reason why we can't use the key for getting the name. If needed we can also add new key attribute. This API is also private for the console so we should be OK with the change.

@eldadfux, here's a PR to add the provider key to the response: https://github.com/appwrite/appwrite/pull/5857

**Review by eldadfux — APPROVED** [review]

**Comment by stnguyen90** [comment]
@TorstenDittmann, anything else before this can be merged?

**Comment by stnguyen90** [comment]
@TorstenDittmann is this good to merge now?

**Review by eldadfux — APPROVED** [review]

**Pull request merged**
