### PR TITLE
Feat : Add frontend for line OAuth

### PR DESCRIPTION
**Pull request by everly-gif**
## What does this PR do?

Add frontend for line OAuth

## Test Plan

Manual

## Related PRs and Issues
https://github.com/appwrite/appwrite/pull/4426/

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by ArmanNik** [comment]
@everly-gif does require only `App ID` and `App Secret` to work? Because if it does not, then we need to add a custom modal here https://github.com/appwrite/console/tree/main/src/routes/console/project-%5Bproject%5D/auth

**Review by ArmanNik — APPROVED** [review]

**Comment by ArmanNik** [comment]
@chenparnasa are the icons ok?

**Comment by everly-gif** [comment]
what's the recommended size for the icons @ArmanNik @chenparnasa . I remember previously we preferred 100 x 100 , has that changed?

**Comment by ArmanNik** [comment]
@everly-gif we use SVGs instead of PNGs for the new console, so size is not an issue since they are vector images :+1:

**Review by christyjacob4 — APPROVED** [review]

**Review by ArmanNik — APPROVED** [review]

**Pull request closed without merging**
