### PR TITLE
Show user's last activity

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

Show users' last activity on users list and detail pages.

## Test Plan

Manual:

### User Last Accessed

image

image

image

### API Key Last Accessed

image

image

image

## Related PRs and Issues

Depends on new Console SDK release and

* https://github.com/appwrite/appwrite/pull/5781

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by eldadfux** [comment]
@stnguyen90 we should omit the time, the user update method happens only once a day and we record the time of the first activity of the day, starting with the 2nd activity the time is out of sync and misleading. The next update will only happen the next day.

**Comment by stnguyen90** [comment]
> @stnguyen90 we should omit the time, the user update method happens only once a day and we record the time of the first activity of the day, starting with the 2nd activity the time is out of sync and misleading. The next update will only happen the next day.

@eldadfux, that's a good idea to reduce confusion. FYI, we still might have some confusing data due to timezones.

**Comment by eldadfux** [comment]
Why can't we take care of timezone on the console side? we should have the information on the timestamp returned from the API. Also, do we explain in the API docs that this timestamp updates once a day?

Anyway, I strongly believe we need to omit the time, the first question we'll get on Discord is why the user activity isn't updating when they see the time is stuck throughout the day. 

BTW, we also have the same issue with API key, we need to fix both.

**Comment by stnguyen90** [comment]
@eldadfux, 

> Why can't we take care of timezone on the console side? we should have the information on the timestamp returned from the API.

Let's say there's been recent activity, but the timestamp is today at `2023-07-20T02:00:00.000Z` because it's still within 24 hours. Since I'm `UTC-07:00`, when the timestamp is localized, it becomes 2023-07-19 (yesterday). 

> Also, do we explain in the API docs that this timestamp updates once a day?

Here's a PR: https://github.com/appwrite/appwrite/pull/5855.

**Comment by eldadfux** [comment]
> @eldadfux,
> 
> > Why can't we take care of timezone on the console side? we should have the information on the timestamp returned from the API.
> 
> Let's say there's been recent activity, but the timestamp is today at `2023-07-20T02:00:00.000Z` because it's still within 24 hours. Since I'm `UTC-07:00`, when the timestamp is localized, it becomes 2023-07-19 (yesterday).
> 
> > Also, do we explain in the API docs that this timestamp updates once a day?
> 
> Here's a PR: [appwrite/appwrite#5855](https://github.com/appwrite/appwrite/pull/5855).

This is fine for me, the goal here was just to show a rough range of your activity. We didn't plan for it to be accurate to the minute. We need to do the same for the API key `LAST ACCESSED` column.

**Comment by stnguyen90** [comment]
> We need to do the same for the API key LAST ACCESSED column.

@eldadfux, I updated it for API keys too.

**Review by eldadfux — APPROVED** [review]

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
