### PR TITLE
feat: accessible tab kbd navigation

### PR DESCRIPTION
**Pull request by TGlide**
## What does this PR do?

Adds accessible tab controls, following the ARIA APG: https://www.w3.org/WAI/ARIA/apg/

## Test Plan

Manual

## Related PRs and Issues

N/A

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by ArmanNik — COMMENTED** [review]
Future improvement suggestion: 

When a tab is selected, and navigation is triggered, the tabs lose focus after the page loads. 
It would be nice to keep the focus on the tab after navigation :thinking:

**Review by ArmanNik — COMMENTED** [review]
Future improvement suggestion (might not be easily doable): 

When a tab is selected, and navigation is triggered, the tabs lose focus after the page loads. 
It would be nice to keep the focus on the tab after navigation :thinking:

**Review by TorstenDittmann — COMMENTED** [review]
I think once @ArmanNik comments has been resolved we can merge it :)

**Comment by TGlide** [comment]
@TorstenDittmann @ArmanNik done 😉

**Comment by TorstenDittmann** [comment]
> @TorstenDittmann @ArmanNik done 😉

tests are failing 👍🏻

**Comment by TGlide** [comment]
> > @TorstenDittmann @ArmanNik done 😉
> 
> tests are failing 👍🏻

Fixed!

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
