### PR TITLE
bugfix: fix/password-recovery-redirect

### LINKED ISSUE #1153: 🐛 Bug Report: Password Recovery Link Redirects to Projects List
### 👟 Reproduction steps

1. Login to your Appwrite account using your Github account/credentials
2. Go to https://cloud.appwrite.io/console/account and click [Recover your password](https://cloud.appwrite.io/recover)
3. Click on the link to reset your Appwrite password

### 👍 Expected behavior

I would be able to rest my password

### 👎 Actual Behavior

It redirected to my Appwrite Console

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by nickaldwin**
## What does this PR do?

- Refactored setPassword function to properly validate password and confirm password fields before submitting.
- Added consistent error handling for password reset and recovery flows.
- Improved user feedback messages for success and error scenarios.
- Updated password reset form UI to enhance usability and clarity.

(Provide a description of what this PR does.)

## Test Plan
```
console on  fix/password-recovery-redirect [!] via  v20.15.0 
❯ npm run test

> test
> TZ=EST vitest run


 RUN  v1.6.0 /home/typecrap/Work/console

 ✓ tests/unit/helpers/array.test.ts (36)
 ✓ tests/unit/helpers/timeConversion.test.ts (90)
 ✓ tests/unit/helpers/date.test.ts (42)
 ✓ tests/unit/helpers/string.test.ts (12)
 ✓ tests/unit/components/paginationInline.test.ts (7)
 ✓ tests/unit/layout/wizard.test.ts (3) 1056ms
 ✓ tests/unit/elements/inputDomain.test.ts (15) 504ms
 ✓ tests/unit/elements/inputPassword.test.ts (11) 522ms
 ✓ tests/unit/elements/inputCron.test.ts (60) 1003ms
 ✓ tests/unit/elements/inputTags.test.ts (6) 745ms
 ✓ tests/unit/elements/form.test.ts (7) 557ms
 ✓ tests/unit/helpers/numbers.test.ts (15)
 ✓ tests/unit/elements/inputSelect.test.ts (7) 390ms
 ✓ tests/unit/components/code.test.ts (6)
 ✓ tests/unit/elements/inputText.test.ts (9) 463ms
 ✓ tests/unit/elements/inputURL.test.ts (9) 440ms
 ✓ tests/unit/elements/inputNumber.test.ts (9) 384ms
 ✓ tests/unit/elements/inputPhone.test.ts (9) 545ms
 ✓ tests/unit/helpers/unit.test.ts (8)
 ✓ tests/unit/elements/inputTextarea.test.ts (8) 423ms
 ✓ tests/unit/elements/button.test.ts (11)
 ✓ tests/unit/elements/inputEmail.test.ts (8) 405ms
 ✓ tests/unit/elements/inputCheckbox.test.ts (5)
 ✓ tests/unit/elements/inputSearch.test.ts (6)
 ✓ tests/unit/components/secret.test.ts (3)
 ✓ tests/unit/helpers/project.test.ts (1)
 ✓ tests/unit/elements/inputProjectId.test.ts (11) 461ms
 ✓ tests/unit/elements/inputId.test.ts (10) 453ms
 ✓ tests/unit/helpers/withPrevious.test.ts (7)
 ✓ tests/unit/elements/inputRadio.test.ts (4)
 ✓ tests/unit/elements/inputSwitch.test.ts (3)
 ✓ tests/unit/components/copy.test.ts (2)
 ✓ tests/unit/components/copyInput.test.ts (2)
 ✓ tests/unit/components/dropTabsItem.test.ts (4)
 ✓ tests/unit/components/tab.test.ts (4)
 ✓ tests/unit/layout/breadcrumbs.test.ts (1)
 ✓ tests/unit/helpers/object.test.ts (1)
 ✓ tests/unit/components/dropList.test.ts (3) 321ms
 ✓ tests/unit/components/tabs.test.ts (1)
 ✓ tests/unit/components/heading.test.ts (1)
 ✓ tests/unit/components/modal.test.ts (1)
```
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues
fixes #1153
(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
yes
(Write your answer here.)

### CODE REVIEW

**Comment by stnguyen90** [comment]
I don't think this addresses the problem. Were you able to reproduce the problem before the change and then see the expected behavior after your change?

**Review by stnguyen90 — COMMENTED** [review]
I don't think this addresses the problem. Were you able to reproduce the problem before the change and then see the expected behavior after your change?

**Comment by nickaldwin** [comment]
> I don't think this addresses the problem. Were you able to reproduce the problem before the change and then see the expected behavior after your change?

**Comment by nickaldwin** [comment]
> I don't think this addresses the problem. Were you able to reproduce the problem before the change and then see the expected behavior after your change?

I apologize i will reproduce the issue again

**Pull request closed without merging**
